---
- hosts: "ror"
  remote_user: "deploy"
  gather_facts: no

  vars:
    letsencrypts_email: tty8747@gmail.com
    ruby_version: "2.2.3"
    user: "deploy"
    home: "/home/{{ user }}"
    rbenv_root: "{{ home }}/.rbenv"
    app_name: "ror-blog"
    application: "{{ home }}/{{ app_name }}"
    site_name: "ruby2.aaaj.ru"
    bundler_ver: "1.3.0"
    repo_git: "git@gitlab.com:tty8747/ror-blog.git"

  roles:
 
     - rbenv # Install rbenv and ruby
     - bundler
