---
 - name: "Installing nginx"
   apt:
      name: nginx
      state: present
   notify: start nginx

 - name: "Push config nginx"
   template:
     src: "templates/nginx.conf.j2"
     dest: "/etc/nginx/nginx.conf"
     owner: root
     group: www-data
     mode: 0644
   notify: reload nginx

 - name: "Push config site to nginx"
   template:
     src: "templates/site_name.conf.j2"
     dest: "/etc/nginx/sites-available/{{ site_name }}.conf"
     owner: root
     group: www-data
     mode: 0644
   notify: reload nginx

 - name: "Enable config"
   file:
    src: "/etc/nginx/sites-available/{{ site_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ site_name }}.conf"
    owner: root
    group: www-data
    state: link
   notify: reload nginx

 - name: rm default
   file:
     path: /etc/nginx/sites-enabled/default
     state: absent
   notify: reload nginx
