image: ubuntu:latest

stages:
# - build
# - delivery
  - deploy

#ansible:
#  image: williamyeh/ansible:ubuntu16.04
#  
#  stage: build
#  script: ansible --version

build:
  image: ruby:2.2.3
  stage: build
  before_script:
    - apt-get update -qy
    - gem install bundler -v 1.3.0
    - bundle install

  script:
    - ruby -v 
    - rails -v
    - bundle exec cap production deploy
#job 2:
#  stage: build
#  script: ls -al
#
#job 3:
#  stage: test
#  script: ls -al

deploy:
   image: ubuntu:latest
   stage: deploy
   before_script :
     - "which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client )"
     - eval $(ssh-agent -s)
     - echo "$SSH_TOKEN" | tr -d '\r' | ssh-add - > /dev/null
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     - ssh-keyscan ruby.aaaj.ru >> ~/.ssh/known_hosts
     - chmod 644 ~/.ssh/known_hosts


   script: 
     - ssh ruby.aaaj.ru -l deploy "ls -al"
