image: ubuntu:latest

stages:
  - build
# - delivery
  - deploy

#ansible:
#  image: williamyeh/ansible:ubuntu16.04
#  
#  stage: build
#  script: ansible --version

build:
# image: ubuntu:16.04
  image: ruby:2.2.3
  stage: build
  before_script:
    - apt-get update -qy
#   - apt-get install -y nodejs
    - "which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$id_rsa" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git clone git@gitlab.com:tty8747/ror-blog.git
    - gem install bundler -v 1.3.0
    - bundle install
    - rbenv rehash
#   - gem install capistrano
#   - gem install rails
#   - cap install

  script:
    - ruby -v 
    - rails -v
#   - bundle exec cap production deploy
#job 2:
#  stage: build
#  script: ls -al
#
#job 3:
#  stage: test
#  script: ls -al

deploy:
   image: ubuntu:latest
   stage: deploy
   before_script :
     - "which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client )"
     - eval $(ssh-agent -s)
     - echo "$SSH_TOKEN" | tr -d '\r' | ssh-add - > /dev/null
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     - ssh-keyscan tty8747.devops.srwx.net >> ~/.ssh/known_hosts
     - chmod 644 ~/.ssh/known_hosts


   script: 
     - ssh tty8747.devops.srwx.net -l deploy "ls -al"
