---
 - name: Update cache
   apt:
     update_cache: '{{ update_cache }}'
     cache_valid_time: '{{ cache_valid_time }}'

 - name: Install dependencies
   apt:
     name: '{{ packages }}'
     state: present
   vars:
     packages:
     - atop
     - git-core
     - curl
     - zlib1g-dev
     - build-essential
     - libssl-dev
     - libreadline-dev
     - libyaml-dev
     - libsqlite3-dev
     - sqlite3
     - libxml2-dev
     - libxslt1-dev
     - libcurl4-openssl-dev
     - python-software-properties
     - libffi-dev
     - postgresql
     - postgresql-contrib
     - libpq-dev
     - nginx
     - letsencrypt
